[package]
name = "arpdump"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive", "debug", "env", "string"] }
libc = "0.2.159"
